apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-demo
  name: docker-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-demo
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
      - image: dewjam/docker-demo:v1
        name: docker-demo
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: index-html
            mountPath: /usr/share/nginx/html
      volumes:
        - name: index-html
          configMap:
            name: docker-demo-data
