apiVersion: v1
kind: Service
metadata:
  name: docker-demo-service
  labels:
    name: docker-demo
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: docker-demo
